//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicManipulation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicManipulation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\UoA\Tasks\C_C_Demo\Downloads\career_images\apps_dev.png.
        /// </summary>
        public static string applicationDev {
            get {
                return ResourceManager.GetString("applicationDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\UoA\Tasks\C_C_Demo\Downloads\career_images\career_default.png.
        /// </summary>
        public static string careerDefault {
            get {
                return ResourceManager.GetString("careerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\Visual Studio 2013\Projects\BasicManipulation\BasicManipulation\icons\careers_icon.png.
        /// </summary>
        public static string careersIcon {
            get {
                return ResourceManager.GetString("careersIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\Visual Studio 2013\Projects\BasicManipulation\BasicManipulation\icons\course_icon.png.
        /// </summary>
        public static string courseIcon {
            get {
                return ResourceManager.GetString("courseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\UoA\Tasks\C_C_Demo\Downloads\career_images\eceCareerGifImage.gif.
        /// </summary>
        public static string eceCareerGifImage {
            get {
                return ResourceManager.GetString("eceCareerGifImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\Visual Studio 2013\Projects\BasicManipulation\BasicManipulation\icons\FacultyEngineeringLogo.png.
        /// </summary>
        public static string eceFacultyLogo {
            get {
                return ResourceManager.GetString("eceFacultyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\UoA\Tasks\C_C_Demo\Downloads\gif\eceGifImageUpdated.gif.
        /// </summary>
        public static string eceGifImage {
            get {
                return ResourceManager.GetString("eceGifImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\UoA\Tasks\C_C_Demo\Downloads\career_images\power_elec.png.
        /// </summary>
        public static string highPowerElectronics {
            get {
                return ResourceManager.GetString("highPowerElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\Visual Studio 2013\Projects\BasicManipulation\BasicManipulation\icons\job_icon.png.
        /// </summary>
        public static string jobIcon {
            get {
                return ResourceManager.GetString("jobIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\Visual Studio 2013\Projects\BasicManipulation\BasicManipulation\icons\prog_icon.png.
        /// </summary>
        public static string programmeIcon {
            get {
                return ResourceManager.GetString("programmeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\UoA\Tasks\C_C_Demo\Downloads\career_images\renew_energy.png.
        /// </summary>
        public static string renewableEnergy {
            get {
                return ResourceManager.GetString("renewableEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\UoA\Tasks\C_C_Demo\Downloads\career_images\career_robotics.png.
        /// </summary>
        public static string robotics {
            get {
                return ResourceManager.GetString("robotics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\Visual Studio 2013\Projects\BasicManipulation\BasicManipulation\icons\logo.png.
        /// </summary>
        public static string universityLog {
            get {
                return ResourceManager.GetString("universityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\ebag753\Documents\UoA\Tasks\C_C_Demo\Downloads\career_images\wireless_comm.png.
        /// </summary>
        public static string wirelessCommunication {
            get {
                return ResourceManager.GetString("wirelessCommunication", resourceCulture);
            }
        }
    }
}
